name: Deploy MMN Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, mmn-backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy code to app folder
        run: |
          cp -r $GITHUB_WORKSPACE/. /opt/mmn-backend/app/

      - name: Deploy backend container
        run: |
          docker compose -f /opt/mmn-backend/docker-compose.yml up -d --force-recreate
