name: Deploy MMN Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, mmn-backend]
    steps:
      - name: Copy code to app folder
        run: |
          cd $GITHUB_WORKSPACE
          cp -r . /root/services/mmn-backend/app/

      - name: Deploy backend container
        run: |
          docker compose -f /root/services/mmn-backend/docker-compose.yml pull
          docker compose -f /root/services/mmn-backend/docker-compose.yml up -d --force-recreate
